apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - |
                  URL=$(curl -Ls -o /dev/null -w %{url_effective} https://en.wikipedia.org/wiki/Special:Random) || exit 1
                  echo "Generated URL: $URL"
                  curl -v -X POST http://todoapp-svc:2336/todos \
                    -H "Content-Type: application/json" \
                    -d "{\"todo\":\"Read $URL\"}"
                  echo -e "\nCurl exit code: $?"
          restartPolicy: OnFailure
