apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: krisnakris/todoapp:2.8.0
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todoapp-config
                  key: FRONTEND_PORT
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todoapp-config
                  key: BACKEND_URL
          volumeMounts:
            - name: todoapp-storage
              mountPath: /usr/src/app/data
        - name: todoapp-backend
          image: krisnakris/todoapp-backend:2.8.0
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todoapp-config
                  key: BACKEND_PORT
      volumes:
        - name: todoapp-storage
          persistentVolumeClaim:
            claimName: todoapp-claim
