apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: krisnakris/todoapp:2.2.5
          env:
            - name: PORT
              value: "3001"
            - name: BACKEND_URL
              value: "http://todoapp-svc:2336"
          volumeMounts:
            - name: todoapp-storage
              mountPath: /usr/src/app/data
        - name: todoapp-backend
          image: krisnakris/todoapp-backend:2.2.1
          env:
            - name: PORT
              value: "3002"
      volumes:
        - name: todoapp-storage
          persistentVolumeClaim:
            claimName: todoapp-claim
