apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: krisnakris/todoapp:1.13.0
          env:
            - name: PORT
              value: "3001"
          volumeMounts:
            - name: todoapp-storage
              mountPath: /usr/src/app/data
      volumes:
        - name: todoapp-storage
          persistentVolumeClaim:
            claimName: todoapp-claim
