apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - configmap.yaml
  - statefulset.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - load-balancer-service.yaml
  - service.yaml
  - cronjob.yaml
images:
  - name: todoapp-kustomization
    newName: krisnakris/todoapp
    newTag: 3.5.0
  - name: todoapp-backend-kustomization
    newName: krisnakris/todoapp-backend
    newTag: 3.5.0
