apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
    - name: todoapp
      port: 2335
      protocol: TCP
      targetPort: 3001
    - name: todoapp-backend
      port: 2336
      protocol: TCP
      targetPort: 3002
